# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github-UserList-Texture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
	pod 'Texture'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxAlamofire'
	pod 'Kingfisher'



  # Pods for Github-UserList-Texture

  target 'Github-UserList-TextureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Github-UserList-TextureUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
